/** Every path in the application, in one place so links and routes cannot drift. */
export const PATHS = {
  statusOverview: '/',
  assignments: '/opdrachten',
  assignmentDetail: '/opdrachten/:assignmentId',
  assignmentQuote: '/opdrachten/:assignmentId/offerte',
  assignmentMonthClose: '/opdrachten/:assignmentId/maandafsluiting',
  signing: '/tekenen',
  signingQuote: '/tekenen/:quoteId',
  allocations: '/inzet',
  costs: '/kosten',
  rates: '/tarieven',
  team: '/team',
  vacancies: '/vacatures',
  vacancyOpenRoles: '/vacatures/open-rollen',
  vacancySetup: '/vacatures/beheer',
  vacancyDetail: '/vacatures/:vacancyId',
  client: '/aanvragen',
  clientRequest: '/aanvragen/nieuw',
  clientAssignment: '/aanvragen/opdracht/:assignmentId',
  receivedQuote: '/aanvragen/offerte/:quoteId',
  admin: '/beheer',
  peers: '/beheer/koppelingen',
  reports: '/rapportage',
  reportAssignment: '/rapportage/opdrachten/:assignmentId',
  wiesProposals: '/beheer/wies',
  login: '/inloggen',
  noAccess: '/geen-toegang',
} as const;
