/** Every path in the application, in one place so links and routes cannot drift. */
export const PATHS = {
  statusOverview: '/',
  tasks: '/taken',
  assignments: '/opdrachten',
  assignmentDetail: '/opdrachten/:assignmentId',
  assignmentFinance: '/opdrachten/:assignmentId/financieel',
  assignmentStaffing: '/opdrachten/:assignmentId/bemensing',
  assignmentBudget: '/opdrachten/:assignmentId/begroting',
  assignmentQuote: '/opdrachten/:assignmentId/offerte',
  assignmentMonthClose: '/opdrachten/:assignmentId/maandafsluiting',
  signing: '/tekenen',
  signingQuote: '/tekenen/:quoteId',
  // Checking a bundle of evidence; open to an invited signer too.
  verifyProof: '/bewijs-controleren',
  quoteApprovals: '/goedkeuren',
  quoteApproval: '/goedkeuren/:quoteId',
  quoteSettings: '/beheer/offertes',
  quoteSender: '/beheer/afzender',
  allocations: '/inzet',
  costs: '/kosten',
  costItem: '/kosten/:costItemId',
  rates: '/beheer/tarieven',
  // Where the rate cards used to live; redirects to `rates`.
  ratesLegacy: '/tarieven',
  team: '/team',
  teamPerson: '/team/:personId',
  vacancies: '/vacatures',
  vacancyOpenRoles: '/vacatures/open-rollen',
  vacancySetup: '/vacatures/beheer',
  functionFramework: '/beheer/functiegebouw',
  vacancyDetail: '/vacatures/:vacancyId',
  client: '/aanvragen',
  clientRequest: '/aanvragen/nieuw',
  clientAssignment: '/aanvragen/opdracht/:assignmentId',
  receivedQuote: '/aanvragen/offerte/:quoteId',
  admin: '/beheer',
  activity: '/beheer/activiteit',
  peers: '/beheer/koppelingen',
  organisations: '/beheer/organisaties',
  roles: '/beheer/rollen',
  reports: '/rapportage',
  reportAssignment: '/rapportage/opdrachten/:assignmentId',
  reportTopic: '/rapportage/:topic',
  wiesProposals: '/beheer/wies',
  login: '/inloggen',
  noAccess: '/geen-toegang',
} as const;
