/** Every path in the application, in one place so links and routes cannot drift. */
export const PATHS = {
  statusOverview: '/',
  assignments: '/opdrachten',
  assignmentDetail: '/opdrachten/:assignmentId',
  assignmentFinance: '/opdrachten/:assignmentId/financieel',
  assignmentStaffing: '/opdrachten/:assignmentId/bemensing',
  assignmentBudget: '/opdrachten/:assignmentId/begroting',
  assignmentQuote: '/opdrachten/:assignmentId/offerte',
  assignmentMonthClose: '/opdrachten/:assignmentId/maandafsluiting',
  signing: '/tekenen',
  signingQuote: '/tekenen/:quoteId',
  allocations: '/inzet',
  costs: '/kosten',
  rates: '/beheer/tarieven',
  // Where the rate cards used to live; redirects to `rates`.
  ratesLegacy: '/tarieven',
  team: '/team',
  teamPerson: '/team/:personId',
  vacancies: '/vacatures',
  vacancyOpenRoles: '/vacatures/open-rollen',
  vacancySetup: '/vacatures/beheer',
  functionFramework: '/beheer/functiegebouw',
  vacancyDetail: '/vacatures/:vacancyId',
  client: '/aanvragen',
  clientRequest: '/aanvragen/nieuw',
  clientAssignment: '/aanvragen/opdracht/:assignmentId',
  receivedQuote: '/aanvragen/offerte/:quoteId',
  admin: '/beheer',
  peers: '/beheer/koppelingen',
  organisations: '/beheer/organisaties',
  reports: '/rapportage',
  reportAssignment: '/rapportage/opdrachten/:assignmentId',
  reportTopic: '/rapportage/:topic',
  wiesProposals: '/beheer/wies',
  login: '/inloggen',
  noAccess: '/geen-toegang',
} as const;
